[package]
name = "rustup-mirror"
version = "0.1.0"
authors = ["Jiajie Chen <jiegec@qq.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.9"
toml = "0.4.10"
url = "1.7.2"
filebuffer = "0.4.0"
rust-crypto = "0.2.36"
clap = "2.32.0"